encoding: utf-8
port: 5678
host: 0.0.0.0

title: znfang
keywords: [znfang, 后端, 算法, 杭州]
description: '到底要做一个什么样的人？'

exclude: [webpack.config.js, package.json, Gemfile, Gemfile.lock, src, node_modules]
plugins: [jekyll-paginate]

permalink: /:title.html
highlighter: rouge
markdown: kramdown
kramdown: 
  auto_ids:       true
  auto_id_prefix: 'id-'
  toc_levels:     '2,3'
  smart_quotes:   lsquo,rsquo,ldquo,rdquo

paginate: 10
repository: znfang/jekyll-template

nickname: znfang
home: http://jekyll-template.xnzone.ml # 微信分享主页信息
IMG_PATH: /img
tongji: baidu_tongji_id
analytics: goole_analytics_id

# Comments  disqus needs vpn
comment-type: 'none' # supported disqus,valine,none
disqus_username: disqus_username
valine_appid: valine_appid
valine_appkey: valine_appkey
